### ISSUE TITLE
About swin_base_patch4_window12_384_22k.pkl

### ISSUE THREAD

**Issue by PixelSegTech** [workforai/SCAN#10]
Hello, thank you for your outstanding contribution. I am very interested in your paper and I am currently reproducing the results. However, I have encountered an issue where I cannot find the swin_base_patch4_window12_384_22k.pkl file. Could you please provide this file. Thank you.

**Comment by PixelSegTech** [comment]
Thank you for your amazing work on this project.

I'm currently experiencing issues when trying to load weights into the model. Specifically, I used the convert-pretrained-swin-model-to-d2.py script to convert swin_base_patch4_window12_384_22k.pth to swin_base_patch4_window12_384_22k.pkl.

However, when loading the converted weights,  I encountered the following issue： ValueError: Unsupported type found in checkpoint! model: <class 'collections.OrderedDict'>

**Comment by yongliu20** [comment]
Hi, thanks for your interest in our work!  We have uploaded the corresponding weight file here: https://drive.google.com/file/d/1MTm_x4Q0mHb962Ye28sqSVtQemEwv5is/view?usp=sharing.
We do not encounter similar problems when loading this weight and maybe you can try the provided weight. Hope this can help you!
