### ISSUE TITLE
关于显卡和训练时间

### ISSUE THREAD

**Issue by shuo1874** [workforai/SCAN#11]
感谢您的优秀工作，请问您使用的什么显卡，大概使用了多少训练时间呢？

**Comment by SuleBai** [comment]
Hi, thanks for your interest.

We conduct the experiments using A100(40GB) and V100(32GB) GPUs.

And when using the default config(bs=32), it takes around 30GB VRAM.

It takes around 18 hours under the [scan_vitL.yaml](https://github.com/yongliu20/SCAN/blob/main/configs/scan_vitL.yaml) config with 8 gpus.
