### ISSUE TITLE
ERROR:root:Model config for ViT-L-14 not found; available models [].

### ISSUE THREAD

**Issue by bingnoi** [workforai/SCAN#2]
wrong when installing dependencies, need access to huggingface?

**Comment by buchannn** [comment]
Hello, I have also encountered this problem, have you solved it?

**Comment by SuleBai** [comment]
Hi @buchannn @bingnoi , this is a bug and we have fixed it. Please check the latest commit.

We have uploaded all the config files contained in the `open_clip` repo.
