### ISSUE TITLE
Issue with Loading Converted Weights Due to Shape Mismatch

### ISSUE THREAD

**Issue by smalllwater** [workforai/SCAN#4]
Thank you for your amazing work on this project.

I'm currently experiencing issues when trying to load weights into the model. Specifically, I used the convert-pretrained-swin-model-to-d2.py script to convert swin_base_patch4_window12_384_22k.pth to swin_base_patch4_window12_384_22k.pkl.

However, when loading the converted weights, I encounter several warnings related to shape mismatches between the checkpoint and the model parameters. Here are some examples of the warnings:

d2.checkpoint.c2_model_loading WARNING: Shape of norm.bias in checkpoint is torch.Size([1024]), while shape of sem_seg_head.pixel_decoder.adapter_1.norm.bias in model is torch.Size([256]).
d2.checkpoint.c2_model_loading WARNING: norm.bias will not be loaded. Please double check and see if this is desired.
d2.checkpoint.c2_model_loading WARNING: Shape of norm.weight in checkpoint is torch.Size([1024]), while shape of sem_seg_head.pixel_decoder.adapter_1.norm.weight in model is torch.Size([256]).
d2.checkpoint.c2_model_loading WARNING: norm.weight will not be loaded. Please double check and see if this is desired.
d2.checkpoint.c2_model_loading WARNING: Shape of norm.bias in checkpoint is torch.Size([1024]), while shape of sem_seg_head.pixel_decoder.layer_1.norm.bias in model is torch.Size([256]).
d2.checkpoint.c2_model_loading WARNING: norm.bias will not be loaded. Please double check and see if this is desired.
d2.checkpoint.c2_model_loading WARNING: Shape of norm.weight in checkpoint is torch.Size([1024]), while shape of sem_seg_head.pixel_decoder.layer_1.norm.weight in model is torch.Size([256]).
d2.checkpoint.c2_model_loading WARNING: norm.weight will not be loaded. Please double check and see if this is desired.
d2.checkpoint.c2_model_loading WARNING: Shape of norm.bias in checkpoint is torch.Size([1024]), while shape of sem_seg_head.predictor.transformer_cross_attention_layers.0.norm.bias in model is torch.Size([256]).

Due to these warnings, it seems that some of the model parameters are not being correctly loaded, which is impacting the performance of the model.

Could you please provide some guidance on how to resolve these shape mismatches? Is there a recommended way to adjust the model or the checkpoint to ensure compatibility? Any insights or suggestions would be greatly appreciated.

Thank you in advance for your help!

**Comment by SuleBai** [comment]
Hi @smalllwater , thanks for your interest in our work.

You may follow the swin model preparation in Mask2Former repo. See [here](https://github.com/facebookresearch/Mask2Former/blob/main/tools/README.md) for reference.

If you have any further questions, please feel free to ask.

**Comment by smalllwater** [comment]
I wanted to take a moment to express my gratitude for your assistance with the issue I was facing regarding the shape mismatches while loading the converted weights. Your guidance was incredibly helpful, and I'm pleased to report that my issue has been resolved successfully.

Thank you for your prompt and detailed response. Your support and the work you do on this project are greatly appreciated.

**Comment by SuleBai** [comment]
Glad I could help. Let me know if you run into any other issues.
