### ISSUE TITLE
Could you provide  a pretrained SCAN-VitB weights?

### ISSUE THREAD

**Issue by Y-Claw** [workforai/SCAN#9]
Could you provide  a pretrained SCAN-VitB weights?

**Comment by SuleBai** [comment]
Hi, we upload the `SCAN-VitB weights` to the original [google drive link](https://drive.google.com/drive/folders/1obgHGQngtQms0u5YUJRnwd4y1IzME-c8?usp=drive_link).

And you can test the base model performance using command like
```
python train_net.py --num-gpu 8 --eval-only --config-file configs/scan_vitB.yaml MODEL.WEIGHTS ./SCAN-vitB.pth DATASETS.TEST \(\"ade20k_full_sem_seg_val\",\) MODEL.CLIP_ADAPTER.REPLACE_RATIO 0.05 MODEL.CLIP_ADAPTER.CLIP_ENSEMBLE_WEIGHT 0.75 MODEL.CLIP_ADAPTER.MASK_THR 0.25
```

Also, please check our latest commit as we modify the config for base model.

**Comment by Y-Claw** [comment]
Thank you very much!
